package com.taylor.easylog


/**
 * A flexible log lib which logging process can be customized through [Interceptor].
 * Inspired by Timber and Logger
 */
object EasyLog {

    /**
     * Priority constant for the println method; use Log.v.
     */
    const val VERBOSE = 2

    /**
     * Priority constant for the println method; use Log.d.
     */
    const val DEBUG = 3

    /**
     * Priority constant for the println method; use Log.i.
     */
    const val INFO = 4

    /**
     * Priority constant for the println method; use Log.w.
     */
    const val WARN = 5

    /**
     * Priority constant for the println method; use Log.e.
     */
    const val ERROR = 6

    /**
     * Priority constant for the println method.
     */
    const val ASSERT = 7

    private val interceptors = mutableListOf<Interceptor<in Nothing>>()
    private val chain = Chain(interceptors)
    private var onetimeInterceptor: Interceptor<*>? = null

    /**
     * The entry point for logging
     * @param message the object to be logged, it could be anything
     * @param priority the log level in logcat
     * @param args the formatted args
     */
    fun log(message: Any, priority: Int = VERBOSE, vararg args: Any) {
        chain.proceed("", message, priority, *args) // tag will auto-generated by interceptor
        onetimeInterceptor?.also { removeInterceptor(it) } // remove one time interceptor
    }

    /**
     * Add one time tag for the next logging
     */
    fun tag(tag: String): EasyLog {
        interceptors.forEach { it.tag = tag }
        return this
    }

    /**
     * Add [Interceptor] for customizing log process
     */
    fun addInterceptor(interceptor: Interceptor<*>) {
        addInterceptor(interceptors.size, interceptor)
    }

    /**
     * Add [Interceptor] at [index] for customizing log process
     */
    fun addInterceptor(index: Int, interceptor: Interceptor<*>) {
        interceptors.add(index, interceptor)
    }

    /**
     * Add one time [Interceptor]
     */
    fun interceptor(interceptor: Interceptor<*>): EasyLog {
        var index = interceptors.indexOfFirst { it.javaClass.simpleName == FormatInterceptor::class.java.simpleName }
        if (index == -1) index = 0
        else index += 1
        interceptors.add(index, interceptor)
        onetimeInterceptor = interceptor
        return this
    }

    /**
     * Remove [interceptor]
     */
    fun removeInterceptor(interceptor: Interceptor<*>) {
        interceptors.remove(interceptor)
    }
}